Update: 1638477026

diff --git a/util_i3prop b/util_i3prop
--- a/util_i3prop
+++ b/util_i3prop
@@ -1,20 +1,11 @@
 #!/bin/sh
 
-# i3-get-window-criteria - Get criteria for use with i3 config commands
-
-# To use, run this script, then click on a window.
-# Output is in the format: [<name>=<value> <name>=<value> ...]
-
-# Known problem: when WM_NAME is used as fallback for the 'title="<string>"' criterion,
-# quotes in "<string>" are not escaped properly. This is a problem with the output of `xprop`,
-# reported upstream: https://bugs.freedesktop.org/show_bug.cgi?id=66807
-
-PROGNAME=`basename "$0"`
+progname=`basename "$0"`
 
 # Check for xwininfo and xprop
 for cmd in xwininfo xprop; do
     if ! which $cmd > /dev/null 2>&1; then
-        echo "$PROGNAME: $cmd: command not found" >&2
+        echo "$progname: $cmd: command not found" >&2
         exit 1
     fi
 done
